DROP TABLE IF EXISTS `Payments`.`payments` ;
DROP TABLE IF EXISTS `Payments`.`cards` ;
DROP TABLE IF EXISTS `Payments`.`accounts` ;
DROP TABLE IF EXISTS `Payments`.`account_status` ;
DROP TABLE IF EXISTS `Payments`.`users` ;
DROP TABLE IF EXISTS `Payments`.`user_types` ;
DROP TABLE IF EXISTS `Payments`.`user_statuses` ;
DROP TABLE IF EXISTS `Payments`.`payment_status` ;
DROP TABLE IF EXISTS `Payments`.`payment_type` ;
